### ISSUE TITLE
The fonts are not displayed correctly in Ubuntu

### ISSUE THREAD

**Issue by axelitus** [bitpressio/docker-for-php-developers-errata#1]
Using the fancy PDF version in Ubuntu displays the fonts incorrectly and thus hinders the book's readability, especially the code listings:
![screenshot-20180522083351-643x588](https://user-images.githubusercontent.com/732441/40380989-25d67f72-5dc0-11e8-87e4-6eeef63dce90.png)

**Comment by axelitus** [comment]
I'm running Ubuntu 18.04 bionic and the issue is that the missing fonts are being replaced by DejaVu Sans (by default):
![screenshot from 2018-05-22 09-51-19](https://user-images.githubusercontent.com/732441/40381110-79722bea-5dc0-11e8-9b8e-bd13028a7d12.png)

To fix this issue we need to tell Ubuntu to substitute the missing fonts with a more appropriate font so that the book displays better. As the OperatorMono font is not free, we will be using a replacement font. I found out that the free and open source font [FiraCode](https://github.com/tonsky/FiraCode) is an excellent font replacement for OperatorMono, so we'll be using that.

First, install the missing fonts running the following command in the terminal:

```bash
$ sudo apt-get install ttf-mscorefonts-installer fonts-firacode
```

After that, we need to tell Ubuntu to substitute the missing fonts for the ones we want instead of the default DejaVu Sans. For that, we need to create/edit the file `~/.config/fontconfig/fonts.conf` and place this [gist contents](https://gist.github.com/axelitus/0b2d25e1b4211c4fdc3d0628b47c2db9) inside. This ill tell Ubuntu what fonts to use instead of the ones we don't have (feel free to experiment and set your preferred fonts instead). The next step is to reset the font cache, run the following command in a terminal:

```bash
$ fc-cache
```

Finally, just open the document and the new fonts should be in place and the book should look beautifully as it was intended:
![screenshot from 2018-05-22 11-00-14](https://user-images.githubusercontent.com/732441/40381738-1efe89cc-5dc2-11e8-84cf-bb3193e35282.png)
![screenshot from 2018-05-22 11-07-05](https://user-images.githubusercontent.com/732441/40381742-20f43c4a-5dc2-11e8-9b54-842edca18ab0.png)

So far I can confirm this works if using Evince or Okular for displaying PDF files.

**Comment by axelitus** [comment]
For the missing font SourceSerifPro-Semibold you could go with SourceSerifPro-Bold or maybe @paulredmond can embed the missing font an release an updated PDF version with it (embedding the other fonts would be difficult due to copyright issues I think).

**Comment by axelitus** [comment]
Actually, I have to say that in Windows it is also not displayed as intended (what I mean is unless you have purchased and installed the OperatorMono font in your system, the code listings won't appear as you designed them).

But nevertheless, in Windows, the readability is not affected, at least with my current setup (Windows 10 Pro + Adobe CC [plus certainly some additional fonts installed by it]).

I'm attaching a screenshot so you can see how it is rendered in Windows:
![2018-05-22_13h49_33](https://user-images.githubusercontent.com/732441/40384078-2e7951c4-5dc8-11e8-8382-4c042e1e187d.png)
![2018-05-22_13h48_56](https://user-images.githubusercontent.com/732441/40384085-339ac28c-5dc8-11e8-877e-7e3f96b41545.png)

So I wasn't even aware that it was not the font you used originally, and maybe that's why you didn't have any issues with it. I'm thinking that you would be better off with a font that you could embed or that is available as the [PDF14 standard fonts](https://kbpdfstudio.qoppa.com/standard-14-pdf-fonts/) (meh :disappointed:) (FireCode is a nice one).

**Comment by axelitus** [comment]
It would be so awesome to have something like web fonts for PDF files :thinking:... but so insecure hehe

**Comment by paulredmond** [comment]
Ya, I might have to switch to Fira Code or something...ugh.

**Comment by paulredmond** [comment]
Thanks to your help, I am working on a PDF update with Fira Mono. I don't want to deal with ligatures and they are opinionated IMO (some people love them, others not so much) and they risk some readability in book form.

For those coming to this issue down the road, Gumroad will be updated with a new version of the PDF with all embedded fonts (including Fira Mono for code) and free to download to all purchasers.

**Comment by pavel-mironchik** [comment]
@paulredmond I recently got your book from Gumroad. I saw in your tweet that "basic" PDF is generated file and there is the "fancy" one with your custom design. I however see files "docker-for-php-developers-basic.pdf" and "docker-php-developers-full.pdf" and the last looks like this:
![screenshot_20180903_125751](https://user-images.githubusercontent.com/7408605/44972188-1fd93680-af7a-11e8-8570-aad5f51dfdae.png)
Am I missing something? I use Okular on Kubuntu 18.04.

**Comment by paulredmond** [comment]
Is that the only place you’re seeing the font being weird? I may have missed a few spots converting the font, if you see it elsewhere feel free to post it here.

**Comment by pavel-mironchik** [comment]
>Is that the only place you’re seeing the font being weird?

Nope, I found such font in:

- listing 4:10, page 48
- listing 4:23, page 60-61
- listing 5:21, page 82

Didn't read the book further page 85.

**Comment by paulredmond** [comment]
@pavel-mironchik yes, I see what you're saying. There are a couple places where the fonts were not converted from Operator to Fira. I am going to go through each listing and update, if you see any more, I'd appreciate if you can post it here! Thanks.

**Comment by paulredmond** [comment]
@pavel-mironchik thanks to your report, I was able to find it in one more listing, and in the chapter page numbers. Thank you so much for taking the time to submit your issues! 🎉 

I don't have an ETA of when I will update the PDF in Gumroad, but the impact should be minimal until I update the file. Thanks again!

**Comment by paulredmond** [comment]
Releasing a new version of the PDF, Mobi, and ePub book soon. Please let me know if you still find any issues with font rendering in the Fancy custom PDF version. All other versions are rendered by Leanpub and shouldn't have any issues.
