### ISSUE TITLE
Chapter 9, Page 181 duplication

### ISSUE THREAD

**Issue by pavel-mironchik** [bitpressio/docker-for-php-developers-errata#11]
Take a look at the screenshot from "fancy" PDF:

![screenshot_20180904_023812](https://user-images.githubusercontent.com/7408605/45001086-f2c56c00-afeb-11e8-9651-a43a7b85c2a9.png)

**Comment by paulredmond** [comment]
Fixed and ready for the next publish release. No ETA on release. Thanks!

**Comment by paulredmond** [comment]
Reopening for further QA before future updated publication.

**Comment by paulredmond** [comment]
Verified in QA preview rendering:

**Fancy Version:**

![image](https://user-images.githubusercontent.com/177773/71868433-532a5900-30cb-11ea-9c19-e667be02c9a0.png)

___

**Leanpub Version:**

![image](https://user-images.githubusercontent.com/177773/71868446-64736580-30cb-11ea-96de-b652e6e19644.png)
