### ISSUE TITLE
Quotes in env breaks xdebug

### ISSUE THREAD

**Issue by zerodahero** [bitpressio/docker-for-php-developers-errata#2]
Following the updates in the errata for the Mac OS setup and Xdebug, if the ip address (and the "remote_log" setting) are in quotes it will not work as expected. Looking in the phpinfo(), these values will show up as quoted in there as well, suggesting they're double quoted.

The solution for me was to just remove the quotes--not sure if this is expected env behavior or not, since something like a password would be really nice to put in quotes.

Thanks for the awesome book! It's been a great help so far!

**Comment by paulredmond** [comment]
@zerodahero thank you very much for making my book better! :+1:

**Comment by paulredmond** [comment]
In case someone else comes along, my errata also included a mistake (oh the irony). The Chapter 4 environment variables should not contain quotes and they've been corrected in the [main errata document](https://github.com/bitpressio/docker-for-php-developers-errata/blob/master/errata.md).
