### ISSUE TITLE
09-Laravel Xdebug - on Windows 10

### ISSUE THREAD

**Issue by avrahamm** [bitpressio/docker-for-php-developers-errata#23]
Hi Paul!
I am on Windows 10.
I followed 09-Laravel Xdebug and watched 10-Laravel Xdebug lessons,
yet xdebug doesn't work.
I tried both 09 lesson and PHPStorm debug configuration yet it doesn't work.
xdebug.ini files content is below.
Thanks!

root@0831e10c26dd:/var/www/html# cat /usr/local/etc/php/conf.d/xdeb
ug.ini
[xdebug]
xdebug.default_enable=1
xdebug.remote_autostart=1
; remote_connect_back is not safe in production!
xdebug.remote_connect_back=1
xdebug.remote_host = 10.0.75.1
;172.17.68.49
xdebug.remote_port=9011
xdebug.remote_enable=1
xdebug.idekey=DOCKER_XDEBUG

; profiling
xdebug.profiler_enabled = 0
xdebug.profiler_output_dir = /var/www/html/storage/logs

root@0831e10c26dd:/var/www/html# cat /usr/local/etc/php/conf.d/dock
er-php-ext-xdebug.ini
zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20170
718/xdebug.so
root@0831e10c26dd:/var/www/html#

**Comment by avrahamm** [comment]
[phpinfo.txt](https://github.com/bitpressio/docker-for-php-developers-errata/files/4014517/phpinfo.txt)

**Comment by avrahamm** [comment]
xdebug.remote_connect_back=1
=>
xdebug.remote_connect_back=0
That's was my problem.
I copied it from book fancy.pdp page 53.

Thanks!

**Comment by paulredmond** [comment]
@avrahamm I was just about to update this issue with the above change you already listed.

Sorry about that! I am in the process of updating the book to fix that very issue, you can see it (and other issues) in the errata doc:

https://github.com/bitpressio/docker-for-php-developers-errata/blob/master/errata.md#bug-listing-49-adding-an-xdebug-ini-file

**Comment by paulredmond** [comment]
After I released my course the way that Docker networking works changed a bit, so I had to adjust the already published book.

**Comment by avrahamm** [comment]
Thanks!
