### ISSUE TITLE
Listing 6.5 label

### ISSUE THREAD

**Issue by zerodahero** [bitpressio/docker-for-php-developers-errata#3]
The listing 6.5 label is for the "Nginx Dockerfile" but it is actually the nginx config that should go in `app.conf`

**Comment by zerodahero** [comment]
Also, just noticed it should actually be "Listing 6.7"

**Comment by paulredmond** [comment]
@zerodahero thank you very much for your report! 👍

**Comment by paulredmond** [comment]
Thanks again! The new version hasn't been released yet, but your fix is in my working draft for the updated PDF.
