### ISSUE TITLE
Chapter 4: update xdebug config via environment variables

### ISSUE THREAD

**Issue by vincentwongso** [bitpressio/docker-for-php-developers-errata#6]
Page 53, doing `docker-compose restart` doesn't seems to update the environment variables inside an existing container. The solution is to rebuild the container to make sure the environment variables are updated in the app container.

Refer to docker's manual here:
https://docs.docker.com/compose/reference/restart/

**Comment by paulredmond** [comment]
Thanks @vincentwongso!

I have a document with Errata and the text will eventually be updated with the corrected text.

Here's the errata reference:

https://github.com/bitpressio/docker-for-php-developers-errata/blob/master/errata.md#no_entry_sign-page-53---incorrect-information-about-env-changes

**Comment by vincentwongso** [comment]
Thanks @paulredmond, I should have checked the errata first.

**Comment by paulredmond** [comment]
No worries @vincentwongso 👍 I hope to get a new release out once I wrap up the videos and collect errata from readers.
