### ISSUE TITLE
select "PHP Web Application" in PHP Storm does not exist

### ISSUE THREAD

**Issue by brendanlawton** [bitpressio/docker-for-php-developers-errata#7]
Hi,

Chapter 4: Development Tools, page 49:

> On the following screen, click the plus (+) button in the top left and select "PHP Web Application" to create a run configuration.

I'm running PHPStorm 2017.3, build 173-3727-138

PHP Web Application is not an available option when adding a new configuration. The available PHP options are:

- App Engine for PHP
- PHP Built-in Web Server
- PHP HTTP Request
- PHP Remote Debug
- PHP Script
- PHP Web Page
- PHPUnit
- PHPSpec

*NB There are also Docker options. Would these also be useful options?

**Comment by paulredmond** [comment]
PHP Remote Debug is what you want, I'm working on updating based on the latest PhpStorm. I'll try to help here as well, let me know if you get stuck.

**Comment by paulredmond** [comment]
@brendanlawton be sure to check out the Chapter 4 errata, it has a few changes that are yet to be updated in the book. Specifically, `xdebug.remote_connect_back` doesn't work anymore (it probably works on Linux) and the errata link shows you the updated settings. XDebug is always a bit complicated to set up:

https://github.com/bitpressio/docker-for-php-developers-errata/blob/master/errata.md#chapter-4-development-tools

**Comment by brendanlawton** [comment]
Thanks @paulredmond 

In the correction for 4.11 I see that the new line for PHP_XDEBUG_REMOTE_HOST is commented out. I take it that this is not supposed to be?

**Comment by brendanlawton** [comment]
Thanks @paulredmond 👍

**Comment by paulredmond** [comment]
Reopening until the updates are published in the book.

**Comment by shaneparsons** [comment]
@paulredmond Additionally, do you think you'd be able to add instructions for VS Code? While the setup is similar to PHP Storm, there are some differences which stopped me from getting the majority of this chapter to work. It could very well be due to the fact that I haven't used xdebug before, but it can't hurt to clarify the steps given the popularity of the editor.

Let me know if you'd rather me create a new issue for this.

**Comment by paulredmond** [comment]
Shane, thanks for the feedback! If you can please create another issue and
detail out the issues you were having that would be greatly appreciated!

Paul
paulrredmond@gmail.com

**Comment by paulredmond** [comment]
The latest QA version of the book has the latest PHPStorm instructions. Until the QA version is published you can reference the errata here to get help with newer versions of PHPStorm - https://github.com/bitpressio/docker-for-php-developers-errata/blob/master/errata.md#chapter-4-development-tools
