### ISSUE TITLE
Incorrect homophone

### ISSUE THREAD

**Issue by johnkramlich** [bitpressio/docker-for-php-developers-errata#8]
Chapter 7.  The following sentence:

You still have to make sure you have environment _parody_.

Should be:

You still have to make sure you have environment _parity_.

**Comment by paulredmond** [comment]
@johnkramlich thanks for the report 😊

**Comment by paulredmond** [comment]
Fixed in QA preview release version:

![image](https://user-images.githubusercontent.com/177773/71868594-05fab700-30cc-11ea-8c16-aa9bd2a29f7f.png)
